"""baseline — full schema parity with current SQLite db.py

Creates every table the SQLite version had, but using Postgres-native types:
  - BIGINT GENERATED BY DEFAULT AS IDENTITY in place of INTEGER PK AUTOINCREMENT
  - JSONB in place of TEXT-holding-JSON
  - TIMESTAMPTZ in place of TEXT-holding-ISO-8601
  - real FK constraints + ON DELETE CASCADE (vs SQLite's unenforced FKs)
  - useful secondary indexes (none in SQLite beyond slug)

Idempotent re-runs not needed — Alembic tracks state via alembic_version.

Revision ID: 0001
Revises:
Create Date: 2026-05-13
"""
from __future__ import annotations

from alembic import op


# revision identifiers, used by Alembic.
revision = "0001_baseline"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ─── orgs ────────────────────────────────────────────────────────────
    op.execute("""
    CREATE TABLE orgs (
        id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name            TEXT NOT NULL,
        country         TEXT,
        tax_id          TEXT,
        billing_address TEXT,
        currency        TEXT,
        timezone        TEXT,
        created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
    )
    """)

    # ─── users ───────────────────────────────────────────────────────────
    # plan_id FK is added as a constraint after plans is created (ALTER below).
    op.execute("""
    CREATE TABLE users (
        id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        email            TEXT NOT NULL UNIQUE,
        name             TEXT,
        password_hash    TEXT,
        avatar_url       TEXT,
        provider         TEXT NOT NULL DEFAULT 'stub',
        org_id           BIGINT REFERENCES orgs(id) ON DELETE SET NULL,
        plan_id          BIGINT,    -- FK added below after plans exists
        minutes_used     NUMERIC(10,2) NOT NULL DEFAULT 0,
        plan_started_at  TIMESTAMPTZ,
        created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
    )
    """)
    op.execute("CREATE INDEX idx_users_org ON users(org_id)")
    # Case-insensitive email lookups — matches db.py's lower(email) usage.
    op.execute("CREATE UNIQUE INDEX idx_users_email_lower ON users(lower(email))")

    # ─── plans ───────────────────────────────────────────────────────────
    op.execute("""
    CREATE TABLE plans (
        id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        slug           TEXT NOT NULL UNIQUE,
        label          TEXT NOT NULL,
        tagline        TEXT,
        price_paise    BIGINT NOT NULL,
        currency       TEXT NOT NULL DEFAULT 'INR',
        minutes_total  INTEGER NOT NULL,
        features       JSONB NOT NULL DEFAULT '[]'::jsonb,
        sort_order     INTEGER NOT NULL DEFAULT 0,
        is_active      BOOLEAN NOT NULL DEFAULT true
    )
    """)
    # Wire users.plan_id → plans.id now that plans exists.
    op.execute("""
    ALTER TABLE users
      ADD CONSTRAINT fk_users_plan
      FOREIGN KEY (plan_id) REFERENCES plans(id) ON DELETE SET NULL
    """)

    # ─── agents ──────────────────────────────────────────────────────────
    # All the JSON columns become JSONB — `_row_to_dict` boilerplate goes away.
    # `published` is BOOLEAN (vs the SQLite INTEGER bool we have today).
    op.execute("""
    CREATE TABLE agents (
        id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id         BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        slug            TEXT NOT NULL UNIQUE,
        name            TEXT NOT NULL,
        sector          TEXT,
        locale          TEXT,
        persona         TEXT,
        greeting        TEXT,
        system_prompt   TEXT NOT NULL DEFAULT '',
        voice           TEXT,
        guardrails      JSONB NOT NULL DEFAULT '[]'::jsonb,
        connectors      JSONB NOT NULL DEFAULT '[]'::jsonb,
        sip_config      JSONB,
        voice_tweaks    JSONB,
        outcomes        JSONB NOT NULL DEFAULT '[]'::jsonb,
        policy          JSONB,
        webhook_url     TEXT,
        webhook_headers JSONB,
        variables       JSONB NOT NULL DEFAULT '{}'::jsonb,
        published       BOOLEAN NOT NULL DEFAULT false,
        published_at    TIMESTAMPTZ,
        created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
    )
    """)
    op.execute("CREATE INDEX idx_agents_user ON agents(user_id)")
    # JSONB GIN index over `variables` — Phase 5 analytics will filter on
    # variables->>'industry' and variables->>'country', so this pays for itself
    # the moment we ship "agents by industry" cards on the admin dashboard.
    op.execute("CREATE INDEX idx_agents_variables_gin ON agents USING GIN (variables)")

    # ─── calls ───────────────────────────────────────────────────────────
    # Token columns are pre-staged for Phase 5; capture lands in gemini_bridge
    # but the schema is here from day 1 so the rollup tables can reference it.
    op.execute("""
    CREATE TABLE calls (
        id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        agent_id       BIGINT NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
        started_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
        ended_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
        duration_s     NUMERIC(10,2),
        outcome        TEXT,
        reason         TEXT,
        summary        TEXT,
        final_message  TEXT,
        extracted      JSONB,
        transcript     TEXT,
        -- Phase-5 fields (nullable until token capture lands)
        input_tokens   BIGINT,
        output_tokens  BIGINT,
        cached_tokens  BIGINT,
        model_id       TEXT,
        cost_paise     BIGINT
    )
    """)
    # Composite index for the most common query: latest N calls per agent.
    op.execute("CREATE INDEX idx_calls_agent_started ON calls(agent_id, started_at DESC)")

    # ─── number_requests ────────────────────────────────────────────────
    op.execute("""
    CREATE TABLE number_requests (
        id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        agent_id        BIGINT NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
        user_id         BIGINT REFERENCES users(id) ON DELETE SET NULL,
        country         TEXT,
        city            TEXT,
        delivery_handle TEXT NOT NULL,
        notes           TEXT,
        status          TEXT NOT NULL DEFAULT 'pending',
        created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
    )
    """)
    op.execute("CREATE INDEX idx_nr_agent ON number_requests(agent_id)")
    op.execute("CREATE INDEX idx_nr_user ON number_requests(user_id)")

    # ─── seed plans (idempotent style not needed — fresh DB) ─────────────
    op.execute("""
    INSERT INTO plans (slug, label, tagline, price_paise, currency, minutes_total, features, sort_order, is_active) VALUES
      ('free',     'Free',     '30 free minutes a month — build, test, preview. Publishing on paid.',
                                    0, 'INR',    30,
                                    '["30 voice minutes / month","1 phone-AI agent in draft","Web embed preview (draft only)","Auto-tagged call log","Publishing requires upgrade"]'::jsonb, 1, true),
      ('starter',  'Starter',  'First real deployment. One agent, 1,000 minutes/mo.',
                                  99900, 'INR',  1000,
                                  '["1,000 voice minutes / month","1 phone-AI agent","Web embed + 1 phone number","Email + WhatsApp call summary","Standard support"]'::jsonb, 2, true),
      ('pro',      'Pro',      'Multi-agent ops. 5,000 minutes, 5 agents.',
                                 399900, 'INR',  5000,
                                 '["5,000 voice minutes / month","5 phone-AI agents","Up to 5 phone numbers","CRM + calendar integrations","Priority support"]'::jsonb, 3, true),
      ('business', 'Business', 'Production scale. 25,000 minutes, unlimited agents.',
                                1499900, 'INR',  25000,
                                '["25,000 voice minutes / month","Unlimited agents + numbers","Webhook + custom CRM","Dedicated SIP route","Onboarding + SLA"]'::jsonb, 4, true)
    """)


def downgrade() -> None:
    # Tables drop in dependency order. CASCADE on FKs makes this safe.
    op.execute("DROP TABLE IF EXISTS number_requests CASCADE")
    op.execute("DROP TABLE IF EXISTS calls CASCADE")
    op.execute("DROP TABLE IF EXISTS agents CASCADE")
    op.execute("ALTER TABLE users DROP CONSTRAINT IF EXISTS fk_users_plan")
    op.execute("DROP TABLE IF EXISTS plans CASCADE")
    op.execute("DROP TABLE IF EXISTS users CASCADE")
    op.execute("DROP TABLE IF EXISTS orgs CASCADE")
