"""teams — org_members + org_invites + agents.org_id

Schema upgrade for multi-user organisations:

  * `org_members` — many users can belong to one org with a role
    (owner / admin / member). Backfilled from the existing 1:1
    `users.org_id` so every founder of a workspace becomes its owner.

  * `org_invites` — pending invites by email with a random token; expire in
    7 days, accept/decline/revoke flips a timestamp (we don't delete so the
    audit trail survives).

  * `agents.org_id` — agents are now owned by orgs, not by individual
    users. The original `agents.user_id` column stays as `created_by` for
    audit; the new permission check is "is caller a member of agent.org_id".

Indexes added:
  - org_members(user_id) — fast lookups for "what orgs does user X see?"
  - org_invites(token) UNIQUE — accept-invite hot path
  - org_invites(lower(email)) — duplicate-invite detection
  - agents(org_id) — every list_agents query reads through this

Revision ID: 0002_teams
Revises: 0001_baseline
Create Date: 2026-05-13
"""
from __future__ import annotations

from alembic import op


revision = "0002_teams"
down_revision = "0001_baseline"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ─── org_members ─────────────────────────────────────────────────────
    op.execute("""
    CREATE TABLE org_members (
      org_id     BIGINT NOT NULL REFERENCES orgs(id) ON DELETE CASCADE,
      user_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      role       TEXT NOT NULL CHECK (role IN ('owner','admin','member')),
      invited_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
      joined_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
      PRIMARY KEY (org_id, user_id)
    )
    """)
    op.execute("CREATE INDEX idx_org_members_user ON org_members(user_id)")

    # Backfill: every user with an existing org_id becomes its owner. The
    # legacy `users.org_id` column stays — it's the "primary org" pointer
    # that the topbar / billing surfaces read; once multi-org UX lands we
    # can revisit dropping it.
    op.execute("""
    INSERT INTO org_members (org_id, user_id, role, invited_by, joined_at)
    SELECT u.org_id, u.id, 'owner', NULL, COALESCE(u.created_at, now())
      FROM users u
     WHERE u.org_id IS NOT NULL
    ON CONFLICT DO NOTHING
    """)

    # ─── org_invites ─────────────────────────────────────────────────────
    op.execute("""
    CREATE TABLE org_invites (
      id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      org_id       BIGINT NOT NULL REFERENCES orgs(id) ON DELETE CASCADE,
      email        TEXT NOT NULL,
      role         TEXT NOT NULL CHECK (role IN ('admin','member')),
      token        TEXT NOT NULL UNIQUE,
      invited_by   BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      expires_at   TIMESTAMPTZ NOT NULL,
      accepted_at  TIMESTAMPTZ,
      declined_at  TIMESTAMPTZ,
      revoked_at   TIMESTAMPTZ,
      created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
    )
    """)
    op.execute("CREATE INDEX idx_org_invites_email ON org_invites(lower(email))")
    op.execute("CREATE INDEX idx_org_invites_org_active "
               "ON org_invites(org_id) "
               "WHERE accepted_at IS NULL AND declined_at IS NULL AND revoked_at IS NULL")

    # ─── agents.org_id ───────────────────────────────────────────────────
    # Add nullable first so the backfill can run, then enforce NOT NULL.
    op.execute("ALTER TABLE agents ADD COLUMN org_id BIGINT REFERENCES orgs(id) ON DELETE CASCADE")
    op.execute("""
    UPDATE agents a SET org_id = u.org_id
      FROM users u
     WHERE a.user_id = u.id
       AND a.org_id IS NULL
       AND u.org_id IS NOT NULL
    """)
    # Any agents that still have no org_id (user with no org_id, shouldn't
    # happen post-Phase-1) get parked under the founder's org so they don't
    # vanish from the listing. Safe to delete this branch once we're sure.
    op.execute("""
    UPDATE agents SET org_id = (
      SELECT org_id FROM users WHERE email = 'dipesh.majumder@webspiders.com' LIMIT 1
    )
    WHERE org_id IS NULL
    """)
    op.execute("ALTER TABLE agents ALTER COLUMN org_id SET NOT NULL")
    op.execute("CREATE INDEX idx_agents_org ON agents(org_id)")


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS idx_agents_org")
    op.execute("ALTER TABLE agents DROP COLUMN IF EXISTS org_id")
    op.execute("DROP TABLE IF EXISTS org_invites CASCADE")
    op.execute("DROP TABLE IF EXISTS org_members CASCADE")
