"""super_admins + audit_log

Phase 3 — platform-level admin.

  * `super_admins` — users who can see across all orgs. A separate table
    (rather than a `users.is_super_admin` flag) so:
       - granting/revoking is naturally append-trail-friendly (we keep
         granted_at and granted_by)
       - the founder seed is idempotent (NOT IN-guarded INSERT)
       - dropping the flag in code is impossible — every check goes
         through the table, not a boolean cached on the user row.

  * `audit_log` — every super-admin write hits this in the same txn as
    the actual mutation. Keeps the forensic trail on disk even if logs
    rotate. JSONB diff so we record `{before, after}` for everything;
    cheap to query later via `target_kind = 'agent' AND target_id = '42'`.

Indexes:
  - audit_log(actor_id, created_at DESC)
  - audit_log(target_kind, target_id) — drill into "who changed agent X?"
  - audit_log(created_at DESC) — global recent feed

Revision ID: 0003_super_admin
Revises: 0002_teams
Create Date: 2026-05-14
"""
from __future__ import annotations

from alembic import op


revision = "0003_super_admin"
down_revision = "0002_teams"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("""
    CREATE TABLE super_admins (
      user_id    BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
      granted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      granted_by BIGINT REFERENCES users(id) ON DELETE SET NULL
    )
    """)

    op.execute("""
    CREATE TABLE audit_log (
      id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      actor_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
      action      TEXT NOT NULL,
      target_kind TEXT,
      target_id   TEXT,
      diff        JSONB,
      ip          INET,
      user_agent  TEXT,
      created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
    )
    """)
    op.execute("CREATE INDEX idx_audit_actor ON audit_log(actor_id, created_at DESC)")
    op.execute("CREATE INDEX idx_audit_target ON audit_log(target_kind, target_id)")
    op.execute("CREATE INDEX idx_audit_recent ON audit_log(created_at DESC)")

    # Seed: founder gets super-admin so the first /admin login works.
    op.execute("""
    INSERT INTO super_admins (user_id, granted_at, granted_by)
    SELECT id, now(), NULL FROM users WHERE email = 'dipesh.majumder@webspiders.com'
    ON CONFLICT (user_id) DO NOTHING
    """)


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS audit_log CASCADE")
    op.execute("DROP TABLE IF EXISTS super_admins CASCADE")
