"""llm_calls — universal LLM-session token + cost ledger

Today's gap: `calls` tracks customer-facing phone conversations
(agent → caller), and Phase 5 wired token + cost there. But every
minute a user spends with Eva, every TTS preview clip, every future
internal LLM use ALSO burns tokens we pay for — and none of it shows
up in the cost dashboard.

Fix: a separate `llm_calls` table that records EVERY LLM session.
Three kinds:
  - 'agent'   — customer-facing phone-AI agent call (mirrors a calls row)
  - 'builder' — Eva-builder session (the user voice-building an agent)
  - 'tts'     — one-shot voice-preview generation (`scripts/gen_voice_samples.py`)

Why a separate table, not an extra column on `calls`:
  - `calls` is the customer record — has webhooks fire, outcomes,
    transcripts, extracted KV. A builder session has none of those.
  - Keeping them separate lets finance query "platform LLM spend" off
    `llm_calls` (the universal ledger) while customer dashboards stay
    on `calls`. No tagging gymnastics.

Linking: when an agent call writes `calls`, the same transaction
writes a matching `llm_calls` row with `kind='agent'` + `call_id`
pointing back. Builder/tts rows have `call_id=NULL`.

Cost-per-minute lives at query time — generated column or computed
in the analytics function. We add it here as a stored generated column
so admin grids can `ORDER BY cost_per_minute_paise DESC` without
re-computing.

Revision ID: 0007_llm_ledger
Revises: 0006_rate_limit_settings
Create Date: 2026-05-14
"""
from __future__ import annotations

from alembic import op


revision = "0007_llm_ledger"
down_revision = "0006_rate_limit_settings"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("""
    CREATE TABLE llm_calls (
      id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      kind            TEXT NOT NULL CHECK (kind IN ('agent','builder','tts')),
      user_id         BIGINT REFERENCES users(id)  ON DELETE SET NULL,
      org_id          BIGINT REFERENCES orgs(id)   ON DELETE SET NULL,
      agent_id        BIGINT REFERENCES agents(id) ON DELETE SET NULL,
      call_id         BIGINT REFERENCES calls(id)  ON DELETE SET NULL,
      started_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
      ended_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
      duration_s      NUMERIC(10,2) NOT NULL DEFAULT 0,
      input_tokens    BIGINT NOT NULL DEFAULT 0,
      output_tokens   BIGINT NOT NULL DEFAULT 0,
      cached_tokens   BIGINT NOT NULL DEFAULT 0,
      model_id        TEXT,
      cost_paise      BIGINT NOT NULL DEFAULT 0,
      -- Generated column: paise per minute. NULL when duration is 0 (zero-
      -- duration session = "session opened but ended immediately"; dividing
      -- by 0 isn't a number, NULL is more honest than 0 paise/min).
      cost_per_minute_paise NUMERIC(12,2) GENERATED ALWAYS AS (
        CASE WHEN duration_s > 0
             THEN (cost_paise::numeric * 60.0) / duration_s
             ELSE NULL END
      ) STORED
    )
    """)
    # Hot indexes:
    #   - org+started for the per-org analytics window
    #   - kind+started for "what's our builder spend trending like"
    #   - call_id for joining back to customer-call records
    op.execute("CREATE INDEX idx_llm_org_started ON llm_calls(org_id, started_at DESC)")
    op.execute("CREATE INDEX idx_llm_kind_started ON llm_calls(kind, started_at DESC)")
    op.execute("CREATE INDEX idx_llm_call ON llm_calls(call_id) WHERE call_id IS NOT NULL")


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS llm_calls CASCADE")
