"""build_sessions — durable Eva-build slot state outside Gemini's context

Why this exists: Eva's build slots (sector_kind, business_name, primary_job,
agent_name) used to live ONLY inside Gemini Live's context window. Any
Gemini-side stream drop without a resume handle — which the cascade Live
model does frequently — landed us in a reconnect with no memory, and Eva
re-asked everything. The transcript-recap-as-one-turn fallback in
`gemini_bridge.run_session` is a mitigation, not a fix: it can be pushed
out of the new session's context as easily as the original turns were.

The fix is to externalise build state to Postgres, keyed by a stable
client-generated `sid` (UUID per build), and inject the known facts into
the system prompt on every (re)connect. This migration adds the table +
its supporting triggers; the app code in gemini_bridge.py + db_pg.py reads
and writes it via the new `note_build_facts` tool.

Lifecycle:
  - INSERT on first note_build_facts call for an (user_id, sid) pair
  - UPDATE on every subsequent call (UPSERT via ON CONFLICT)
  - status flips to 'committed' when save_agent fires, with
    committed_agent_id pointing at the resulting agents row
  - status 'abandoned' is set by a periodic cleanup over the
    partial index (in_progress + updated_at older than N hours)

Revision ID: 0011_build_sessions
Revises: 0010_db_audit_phase9b
Create Date: 2026-05-14
"""
from __future__ import annotations

from alembic import op


revision = "0011_build_sessions"
down_revision = "0010_db_audit_phase9b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ── table ────────────────────────────────────────────────────────────
    # status is a free TEXT with a CHECK constraint rather than a PG ENUM:
    # adding a new value to an ENUM mid-flight is a schema-locking pain,
    # and we already use the same pattern in agents.published / invites.
    op.execute("""
    CREATE TABLE build_sessions (
        id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        sid                 TEXT NOT NULL,
        user_id             BIGINT REFERENCES users(id) ON DELETE CASCADE,
        org_id              BIGINT REFERENCES orgs(id) ON DELETE CASCADE,
        sector_kind         TEXT,
        business_name       TEXT,
        primary_job         TEXT,
        agent_name          TEXT,
        extras              JSONB NOT NULL DEFAULT '{}'::jsonb,
        status              TEXT NOT NULL DEFAULT 'in_progress',
        committed_agent_id  BIGINT REFERENCES agents(id) ON DELETE SET NULL,
        created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
        CONSTRAINT build_sessions_status_chk CHECK
            (status IN ('in_progress', 'committed', 'abandoned'))
    )
    """)

    # ── indexes ──────────────────────────────────────────────────────────
    # 1. (user_id, sid) UNIQUE drives the upsert path. One row per browser
    #    build per user. user_id nullable for unauthenticated dev sessions
    #    (NULLS NOT DISTINCT keeps multi-anon builds isolated — without
    #    this, two anon builders both inserting sid='abc' could collide.)
    op.execute("""
    CREATE UNIQUE INDEX build_sessions_user_sid_uniq
      ON build_sessions(user_id, sid) NULLS NOT DISTINCT
    """)
    # 2. Partial index over in-progress rows ordered by updated_at — used
    #    by the abandonment-cleanup job ("set status='abandoned' WHERE
    #    status='in_progress' AND updated_at < now() - interval '24h'").
    #    Partial keeps the index tiny: committed rows accumulate forever,
    #    but the only ones we ever scan by updated_at are the live ones.
    op.execute("""
    CREATE INDEX idx_build_sessions_inprogress_updated
      ON build_sessions(updated_at DESC)
      WHERE status = 'in_progress'
    """)
    # 3. Multi-tenant analytics index — "builds started by this org in
    #    the last 7 days". Mirrors idx_calls_org_started from 0010.
    op.execute("""
    CREATE INDEX idx_build_sessions_org_created
      ON build_sessions(org_id, created_at DESC)
    """)

    # ── updated_at trigger ───────────────────────────────────────────────
    # Same shape as the calls_org_stamp trigger from 0010 — we want every
    # UPDATE to bump updated_at automatically so the cleanup job's
    # partial index stays sorted correctly. App code can ignore the
    # column entirely.
    op.execute("""
    CREATE OR REPLACE FUNCTION build_sessions_touch_updated_at() RETURNS trigger AS $$
    BEGIN
      NEW.updated_at := now();
      RETURN NEW;
    END;
    $$ LANGUAGE plpgsql
    """)
    op.execute("""
    CREATE TRIGGER build_sessions_touch_updated_at_trigger
      BEFORE UPDATE ON build_sessions
      FOR EACH ROW EXECUTE FUNCTION build_sessions_touch_updated_at()
    """)


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS build_sessions_touch_updated_at_trigger ON build_sessions")
    op.execute("DROP FUNCTION IF EXISTS build_sessions_touch_updated_at()")
    op.execute("DROP INDEX IF EXISTS idx_build_sessions_org_created")
    op.execute("DROP INDEX IF EXISTS idx_build_sessions_inprogress_updated")
    op.execute("DROP INDEX IF EXISTS build_sessions_user_sid_uniq")
    op.execute("DROP TABLE IF EXISTS build_sessions")
